export const IS_LOADING = "IS_LOADING"
// calendars
export const GET_CALENDARS_SUCCESS = "GET_CALENDARS_SUCCESS"
export const GET_CALENDARS_FAILURE = "GET_CALENDARS_FAILURE"
export const EDIT_USER_CALENDAR_SUCCESS = "EDIT_USER_CALENDAR_SUCCESS"
export const EDIT_USER_CALENDAR_FAILURE = "EDIT_USER_CALENDAR_FAILURE"
export const SET_USER_CALENDAR = "SET_USER_CALENDAR"
export const SET_CALENDAR_SUBSCRIPTION_ID = "SET_CALENDAR_SUBSCRIPTION_ID"
export const SUBSCRIBE_TO_CALENDAR_SUCCESS = "SUBSCRIBE_TO_CALENDAR_SUCCESS"
export const SUBSCRIBE_TO_CALENDAR_FAILURE = "SUBSCRIBE_TO_CALENDAR_FAILURE"
export const UNSUBSCRIBE_CALENDAR_SUCCESS = "UNSUBSCRIBE_CALENDAR_SUCCESS"
export const UNSUBSCRIBE_CALENDAR_FAILURE = "UNSUBSCRIBE_CALENDAR_FAILURE"

// events
export const GET_CALENDAR_EVENTS_SUCCESS = "GET_CALENDAR_EVENTS_SUCCESS"
export const GET_CALENDAR_EVENTS_FAILURE = "GET_CALENDAR_EVENTS_FAILURE"
export const GET_SUBSCRIBED_CALENDAR_EVENTS_SUCCESS =
  "GET_SUBSCRIBED_CALENDAR_EVENTS_SUCCESS"
export const GET_SUBSCRIBED_CALENDAR_EVENTS_FAILURE =
  "GET_SUBSCRIBED_CALENDAR_EVENTS_FAILURE"
export const RESET_SUBSCRIBED_CALENDAR_EVENTS =
  "RESET_SUBSCRIBED_CALENDAR_EVENTS"
export const CREATE_CALENDAR_EVENT_SUCCESS = "CREATE_CALENDAR_EVENT_SUCCESS"
export const EDIT_CALENDAR_EVENT_SUCCESS = "EDIT_CALENDAR_EVENT_SUCCESS"
export const DELETE_CALENDAR_EVENT_SUCCESS = "DELETE_CALENDAR_EVENT_SUCCESS"
export const CRUD_OPS_CALENDAR_EVENT_FAILURE = "CRUD_OPS_CALENDAR_EVENT_FAILURE"
export const SET_USER_CALENDAR_EVENT = "SET_USER_CALENDAR_EVENT"
